name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Github Docker Registry
      run: |
        echo $CR_PAT | docker login ghcr.io -u Abstractolotl --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    - name: Set Tag
          id: vars
          run: echo ::set-output name=tag::$(echo $(date +%s))
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/abstractolotl/azplace-frontend:${{steps.vars.outputs.tag}} --tag ghcr.io/abstractolotl/azplace-frontend:latest
    - name: Push the Docker image
      run: docker push ghcr.io/abstractolotl/azplace-frontend --all-tags