name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  version:
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'automated version patch' && !startsWith(github.ref, 'refs/tags/') }} 
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TU_PUSH }}
      - name: Install dependencies
        run: npm install
      - name: GitHub Configuration
        run: |
          git config --global user.email "info@ancozockt.de"
          git config --global user.name "Ancocodet"
      - name: Patch version
        run: VERSION=$(npm version patch -m "automated version patch" --force)
      - name: Push changes
        run: |
          git push
          git push --tags

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - name: Login to Github Docker Registry
      run: |
        echo $CR_PAT | docker login ghcr.io -u Abstractolotl --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/abstractolotl/azplace-frontend:$(echo $(date +%s)) --tag ghcr.io/abstractolotl/azplace-frontend:latest
    - name: Push the Docker image
      run: docker push ghcr.io/abstractolotl/azplace-frontend --all-tags

    - name: Trigger helmchart action
      run: |
        curl -XPOST -u "$USERNAME:$CR_PAT" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/Abstractolotl/azplace-helmcharts/dispatches --data '{"event_type": "azplace-frontend update"}'
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
        USERNAME: ${{ secrets.USERNAME }}