name: Build Test

on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install -g http-server
        npm install
    - name: Run build process
      run: |
        npm run build